### ISSUE TITLE
可以增加背景图以及按键控制嘛？

### ISSUE THREAD

**Issue by airsimonhan** [ccoode/timer#1]
感谢提供优秀的源码，请问大侠，可以增加背景图以及按键控制嘛？

**Comment by dgeibi** [comment]
按键控制可以给个大概的方案吗

**Comment by airsimonhan** [comment]
比如正方的暂停和开始的按键用A来控制，停止键用S来控制；反方的暂停和开始用Z来控制，停止用X来控制；双方的切换用G来控制。
这个好实现吗？

以及如果正方和反方的发言计时是分开的，正方除自由辩论以外总计时14分钟，反方也是一样。各个环节的时间由正方和反方自己分配，细则如下。
1开篇立论阶段
1）正方一辩陈词
2）反方任意辩手反驳
3）反方一辩陈词
4）正方任意辩手反驳

2质询阶段
质询环节按照质询方计时原则，即质询和回答时间均算在质询方时间内。
1）正方二辩对反方二辩质询：质询方发问，被质询方只能回答，质询方可以打断。
2）反方二辩对正方二辩质询：质询方发问，被质询方只能回答，质询方可以打断。
3）正方任意辩手质询小结
4）反方任意辩手质询小结

3暂停环节
本环节中，队伍有3分钟的时间进行修整，调整自己的方案。

4自由辩论环节
双方各计时4分钟，交替发言，一方发言完毕另一方发言开始。正方先开始发言。

5总结陈词环节  
1）反方三辩结辩
2）正方三辩结辩

**Comment by dgeibi** [comment]
@airsimonhan 你可以在 config.js (https://github.com/ccoode/timer/blob/gh-pages/config.js) 设置环节和时间

**Comment by dgeibi** [comment]
你可以在 https://ccoode.github.io/timer/ 试用下快捷键

- `A`：正方开始和暂停
- `Q`：正方停止和重置
- `L`：反方开始和暂停
- `P`：反方停止和重置
- `G`：双方切换
- `N`：下一个环节

**Comment by dgeibi** [comment]
@airsimonhan 你可以在 config.js 设置背景图url和不透明度了
